### ISSUE TITLE
Data menu drop-down mismatch

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/content-x#10]
Menu items in the "Data" drop-down should match both the order and text of the buttons on it the homepage. I.e.:
- "Publish Data" should be listed first
- Change "Discover Data" to "Search Data"

**Comment by servilla** [comment]
> Change "Discover Data" to "Search Data"

I would recommend replacing "Search Data" with either "Discover Data" or "Find Data" (this is the md file name). The literal interpretation of "Search Data" means search inside the data, whereas the other two imply looking at a corpus of data - just my opinion.

**Comment by clnsmth** [comment]
"Find Data" works for me
