### ISSUE TITLE
Link "Login" to the Data Portal login

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/content-x#11]
Until Data Portal features are integrated into web-x, or at least a bit further along, the "Login" menu item should resolve to https://portal.edirepository.org/nis/login.jsp?

**Comment by clnsmth** [comment]
How does this sound @servilla?

**Comment by servilla** [comment]
WFM, but note that it is not just Data Portal features - once we add anything to web-x that must identify the user, we'll need to re-enable the local login.

**Comment by clnsmth** [comment]
Fixed by PASTAplus/web-x@ea8083e6966bb957c909cb4f5abe4867dc710c1b
