### ISSUE TITLE
Footer navigation

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/content-x#14]
1. Menu items displayed in the footer navigation should match the menu items displayed at the top of the page. I.e.:
    - Change "Support" to "Help & Support"
    - Add "Login"

3. Capitalize menu titles in the footer navigation to distinguish them from sub items. E.g.: "Data" should be "DATA"

4. Left align both the menu titles and menu items. Currently they are center aligned.

**Comment by servilla** [comment]
> Add "Login"

The login menu item is dynamic and changes when the user session is active. I would not add it to the footer navigation.

**Comment by servilla** [comment]
> Capitalize menu titles in the footer navigation to distinguish them from sub items. E.g.: "Data" should be "DATA"
> Left align both the menu titles and menu items. Currently they are center aligned.

IMO, the footer navigation is good as is it gets w/o re-engineering. Your change suggestions can be adjusted to fit better, but I don't think there is any gain to visual asthetics for functionality (see below):

![image](https://user-images.githubusercontent.com/2224723/158911534-945ec6dd-00ea-4611-b60f-cae3ace9b89b.png)
