### ISSUE TITLE
Footer signature

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/content-x#15]
1. The text in the footer signature should be our mission as stated in the "About EDI" page (i.e. _Preserving environmental data for open and reproducible science, to promote synthesis across space and time, and to aid in the assessment of environmental change and its consequences._) and should be left aligned with the title (currently these are center aligned). 

2. There's a little too much space around the footer signature. Items should be grouped closer together.
Current:
![sig_bad](https://user-images.githubusercontent.com/25492069/158658862-7da34abc-2dc4-451c-8528-5c3058eabc9c.PNG)
Suggested:
![sig_good](https://user-images.githubusercontent.com/25492069/158658915-198d0411-0677-433a-bbd9-5c2bd603411a.PNG)

**Comment by servilla** [comment]
Mostly done with https://github.com/PASTAplus/web-x/commit/689fa5075d04be292ddbd2a114e8e0a8f84c39f0
