### ISSUE TITLE
Explanation of 50M cells limitation in dex

### ISSUE THREAD

**Issue by kzollove** [PASTAplus/content-x#20]
A short paragraph should be added to the [Data Exploration](https://github.com/PASTAplus/content-x/blob/main/templates/resources/data-exploration.md) file explaining the size constraint of dex

**Comment by clnsmth** [comment]
Thanks @kzollove. Please submit as a PR.

**Comment by clnsmth** [comment]
Fixed by PASTAplus/content-x@3516eae25721dd94aba3de9eb930c05516d66a01
