### ISSUE TITLE
Images are not sized correctly across many pages

### ISSUE THREAD

**Issue by servilla** [PASTAplus/content-x#3]
Images in the MD files are not size-controlled, and the same issue is carried over into the HTML files. Images that are referenced in the MD should either be sized correctly or the image links should be wrapped in the corresponding HTML + CSSS to size them correctly. For example:
```
...
Publishing a [data package](/resources/the-data-package) in the EDI Data Repository can be done manually via the EDI Data Portal, or programmatically using the EDIutils R package or the REST API. Across these three methods, the same general pattern is always followed: login, reserve a data package identifier, evaluate the data package, and publish the data package.

<p style="text-align: center">
    <img alt="publish" src="/static/images/publish.png" style="max-height: 10vmin;"/>
</p>

>We recommend [creating a test version](/resources/repository-environments) of a data package for review before publishing the final version.
...
```

See working example in https://github.com/PASTAplus/content-x/blob/main/templates/resources/publishing-a-data-package.md

**Comment by clnsmth** [comment]
@servilla @sgclarkevt The size control example (above) seems like a good solution works since it works in both the GitHub markdown preview and the HTML version of the page in web-x. See here: https://github.com/PASTAplus/content-x/blob/test_links/templates/resources/citing-data.md

**Comment by servilla** [comment]
We should discuss how to best format images and set a standard for any contributed content. I don't know HTML and CSS well enough to make a recommendation, but it seems like a combination of image `height` and `width` along with the appropriate CSS style is necessary for consistent scaling across images.

We should also decide if we want any image decoration (border lines, shadows, etc) across all images.

Note that in my example above, the `max-height: 10vmin` is probably not being used correctly since they refer to viewport scaling and responsive design (i.e., device scaling), which seems to become more complicated when you have the sidebar component of the page.

**Comment by clnsmth** [comment]
For now, images will be added to markdown files via the HTML img element and size controlled using percent of image width (e.g. `<img src="/static/images/access.png" width="55%">`

**Comment by clnsmth** [comment]
These changes have been implemented in the `main` branch.

**Comment by clnsmth** [comment]
Close, but image sizing is still an issue. There's a small but discernible difference between GitHub Preview and web-x rendering. This seems to be a result of the different viewport sizes in these two environments, especially when the corresponding web-x page contains a sidebar.

A solution might be to add offset values in web-x/utilities/build.py depending on page type. I'll experiment with this.

**Comment by clnsmth** [comment]
The adopted solution is to build the webpage locally and manually resize images on a case by case basis. There is no offset value that works well across all pages.
