### ISSUE TITLE
Link "Search Data" to the Data Portal search interface

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/content-x#8]
The "Search Data" button on the home page, and menu item, should probably link directly to the advanced search interface of the EDI Data Portal rather than the "Finding Data" page. The Data Portal search interface handles the vast majority of use cases and the "Finding Data" page provides extra help if anyone needs it.

**Comment by servilla** [comment]
Done with https://github.com/PASTAplus/web-x/commit/8022456dd530212d61a091b40084141a13a7939e
